"""Fixed typo in goals

Revision ID: 6be8ec0db0a1
Revises: 894d8acd0f1e
Create Date: 2025-06-29 13:42:30.392839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6be8ec0db0a1'
down_revision = '894d8acd0f1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.alter_column('saved_amount',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.alter_column('saved_amount',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###
