"""Add transaction-labels many-to-many and drop old label column

Revision ID: d22d8cc8d7b4
Revises: d0f58efdf281
Create Date: 2025-06-29 23:11:14.181003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd22d8cc8d7b4'
down_revision = 'd0f58efdf281'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('label')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
